=== bahaeddine73/Site-Web/XML/game_studios.dtd
<!ENTITY % monthval "(1|2|3|4|5|6|7|8|9|10|11|12)">
<!ENTITY % dayval
	 "(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)">  
<!ENTITY % year "CDATA"> 
<!ENTITY % amp  "&#38;">


<!ENTITY % inline "img | keyword | a | highlight">
<!ENTITY % datainline "(#PCDATA | %inline; )*">
<!ENTITY % datainlineul "(#PCDATA | p | %inline; | ul)*">

<!ENTITY % coreattrs
	 "id       ID      #IMPLIED
	  class    CDATA   #IMPLIED
	  title    CDATA   #IMPLIED"
>

<!ENTITY % URI "CDATA">
 <!-- a Uniform Resource Identifier, see [RFC2396] -->

<!ENTITY % Length "CDATA">
<!-- nn for pixels or nn% for percentage length -->


<!ENTITY % Text "CDATA">
    <!-- used for titles etc. -->

    
<!ELEMENT game_studios
	  (studiodata,citation?,overview,notable_games,illustrations?)>

<!ATTLIST game_studios
	  %coreattrs;
	  id  ID #REQUIRED
	  main_genre    %Text;   #IMPLIED
	  status    (active|defunct)  #IMPLIED
	  year_of_first_game_published      %year;   #REQUIRED>

<!ELEMENT studiodata (name,headquarters+,founded,key_people+,number_of_employees)>
<!ATTLIST studiodata
	  %coreattrs;>

<!ELEMENT name %datainline;>
<!ATTLIST name
	  %coreattrs;>

<!ELEMENT headquarters %datainline;>
<!ATTLIST headquarters
	  %coreattrs;>

<!ELEMENT founded EMPTY>
<!ATTLIST founded
	  %coreattrs;
	  year     %year;       #REQUIRED
	  month    %monthval;   #IMPLIED
	  day      %dayval;     #IMPLIED
	  >

<!ELEMENT key_people %datainline;>
<!ATTLIST key_people
	  %coreattrs;
	  title  %Text;   #IMPLIED>

<!ELEMENT number_of_employees %datainline;>
<!ATTLIST number_of_employees
	%coreattrs;
	year     %year;       #IMPLIED
	month    %monthval;   #IMPLIED
	>

<!ELEMENT citation %datainline;>
<!ATTLIST citation
	  %coreattrs;
	  author %Text; #REQUIRED>



<!ELEMENT overview (history,milestones,current_projects*)>
<!ATTLIST overview
	  %coreattrs;
	  >


<!ELEMENT history %datainlineul;>
<!ATTLIST history
	  %coreattrs;
	  >

<!ELEMENT milestones %datainlineul;>
<!ATTLIST milestones
	  %coreattrs;
	  >


<!ELEMENT current_projects %datainlineul;>
<!ATTLIST current_projects
	  %coreattrs;
	  >



<!ELEMENT notable_games (game+)+>

<!ELEMENT game (gamedata,description,awards*)>
<!ATTLIST game
      %coreattrs;
      >

<!ELEMENT gamedata (game_name,released,publisher,platforms,genre)>
<!ATTLIST gamedata
				%coreattrs;>


<!ELEMENT game_name %datainline;>
<!ATTLIST game_name
		%coreattrs;>


<!ELEMENT released EMPTY>
<!ATTLIST released
		%coreattrs;
		year     %year;       #REQUIRED
		month    %monthval;   #IMPLIED?
		day      %dayval;     #IMPLIED
		>


<!ELEMENT publisher %datainline;>
<!ATTLIST publisher
		%coreattrs;>


<!ELEMENT platforms %datainline;>
<!ATTLIST platforms
		%coreattrs;>


<!ELEMENT genre %datainline;>
<!ATTLIST genre
		%coreattrs;>


<!ELEMENT description %datainlineul;>
<!ATTLIST description
    	%coreattrs;>


<!ELEMENT awards %datainlineul;>
<!ATTLIST awards
		%coreattrs;>



<!ELEMENT ul (li+)>

<!ELEMENT li %datainlineul;>
<!ATTLIST li
	  %coreattrs;
	  year     %year;       #REQUIRED
      month    %monthval;   #IMPLIED
      day      %dayval;     #IMPLIED
	  >


<!ELEMENT illustrations (img+)>
<!ATTLIST illustrations
	  %coreattrs;
	  >


<!ELEMENT img EMPTY>
<!ATTLIST img
	  %coreattrs;
	  src         %URI; #REQUIRED
	  alt         %Text; #REQUIRED
	  longdesc    %URI;          #IMPLIED
	  height      %Length;       #IMPLIED
	  width       %Length;       #IMPLIED
	  >



<!ELEMENT a (#PCDATA)*>
<!ATTLIST a
  %coreattrs;
  href        %URI;          #IMPLIED
>


<!ELEMENT highlight %datainline;>
<!ATTLIST highlight
	  %coreattrs;
	  >

<!ELEMENT p %datainline;>
<!ATTLIST p 
	  %coreattrs;
	  >

=== bahaeddine73/Site-Web/XML/Ubisoft-studio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game_studios SYSTEM "game_studios.dtd">
<game_studios status="active" main_genre="Action-adventure" year_of_first_game_published="1986" id="2">
    <studiodata>
        <name>Ubisoft</name>
        <headquarters>Montreuil, France</headquarters>
        <founded day="28" month="3" year="1986"/>
        <key_people title="co-founder">Yves Guillemot</key_people>
        <key_people title="CEO">Yves Guillemot</key_people>
        <number_of_employees month="2" year="2025">Around 20,000</number_of_employees>
    </studiodata>
    <citation author="Yves Guillemot">We aim to create unique and unforgettable experiences for players around the world.</citation>
    <overview>
        <history>
            <p>Founded in 1986, Ubisoft is known for popular franchises such as "Assassin's Creed", "Far Cry", and "Rainbow Six".</p>
        </history>
        <milestones>
            <ul>
                <li year="2007">Release of "Assassin's Creed".</li>
                <li year="2012">Launch of "Far Cry 3".</li>
                <li year="2014">Release of "Watch Dogs".</li>
                <li year="2020">Launch of "Assassin's Creed Valhalla".</li>
                <li year="2021">Release of "Far Cry 6".</li>
            </ul>
        </milestones>
        <awards>
            <ul>
                <li year="2007">BAFTA Games Award for Best Game (Assassin's Creed).</li>
                <li year="2014">The Game Awards - Best Action/Adventure (Watch Dogs).</li>
            </ul>
        </awards>
        <current_projects>
            <p>Ubisoft has ongoing projects, including future titles in the "Assassin's Creed" and "Far Cry" franchises, as well as potential remasters of older games for next-gen consoles.</p>
        </current_projects>
    </overview>
    <notable_games>
        <game>
            <gamedata>
                <game_name>Assassin's Creed Valhalla</game_name>
                <released year="2020"/>
                <publisher>Ubisoft</publisher>
                <platforms>PlayStation 4, 5, Xbox One, Series X/S, PC</platforms>
                <genre>Action-adventure, RPG</genre>
            </gamedata>
            <description>
                <p>"Assassin's Creed Valhalla" takes place in the Viking era, allowing players to explore and conquer England and Norway in a detailed open-world environment.</p>
            </description>
        </game>
        <game>
            <gamedata>
                <game_name>Far Cry 6</game_name>
                <released year="2021"/>
                <publisher>Ubisoft</publisher>
                <platforms>PlayStation 4, 5, Xbox One, Series X/S, PC</platforms>
                <genre>First-person shooter</genre>
            </gamedata>
        </game>
    </notable_games>
    <illustrations>
        <img src="../Images/Ubisoftstudio/studiophoto.png" alt="Ubisoft studio logo"/>
        <img src="../Images/Ubisoftstudio/photo_of_the_game1.png" alt="Ubisoft studio logo"/>
        <img src="../Images/Ubisoftstudio/photo_of_the_game2.png" alt="Ubisoft studio logo"/>
        <img src="../Images/Ubisoftstudio/photo_of_the_game3.png" alt="Ubisoft studio logo"/>
        <img src="../Images/Ubisoftstudio/photo_of_the_game4.png" alt="Ubisoft studio logo"/>
    </illustrations>
</game_studios>

=== bahaeddine73/Site-Web/XML/FromSoftware.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game_studios SYSTEM "game_studios.dtd">
<game_studios status="active" main_genre="Soulslike" year_of_first_game_published="1994" id="4">
<studiodata>
  <name> FromSoftware </name>
  <headquarters> Tokyo, Japan </headquarters>
  <founded day="1" month="11" year="1986"/>
  <key_people title="founder"> Naotoshi Zin </key_people>
  <key_people title="president/representative director"> Hidetaka Miyazaki </key_people>
  <number_of_employees month="6" year="2024"> 423 </number_of_employees>
</studiodata>
<citation author="Hidetaka Miyazaki">
  I want to preface this by saying I absolutely suck at video games,
</citation>
<overview>
  <history>
    <p>
      FromSoftware is a Japanese video game development and publishing company. It was founded by Naotoshi Zin in Tokyo
      on November 1, 1986. Initially a developer of business software, the company released their first video game,
      King's Field, for the PlayStation in 1994. Its success shifted FromSoftware to focus fully on games, with them
      producing two more King's Field games before the first release of the mecha shooter series Armored Core in 1997.
    </p>

    <p>

      By the 2000s, FromSoftware's releases included the Echo Night, Shadow Tower, Lost Kingdoms, Otogi, and Another
      Century's Episode series. The company achieved breakout success by the 2010s with Demon's Souls and the Dark Souls
      trilogy of action role-playing games. Often cited among the greatest video games ever made, their emphasis on high
      difficulty and environmental storytelling led to the creation of the Soulslike subgenre that includes
      Bloodborne (2015), Sekiro (2019), and Elden Ring (2022).
    </p>

    <p>
      Hidetaka Miyazaki, creator and director of Dark Souls, has served as FromSoftware's representative director and
      president since 2014, with Zin remaining as an advisor. Miyazaki directs and designs the majority of the company's
      games in addition to his executive duties. FromSoftware is owned primarily by Kadokawa Corporation, with minority
      stakes by Tencent subsidiary Sixjoy Hong Kong and Sony Interactive Entertainment. FromSoftware usually
      self-publishes in Japan and has partnered with publishers such as Agetec, Sony, Bandai Namco Entertainment,
      Sega, Capcom, Nintendo and Plaion internationally.
    </p>
  </history>
  <milestones>
    <ul>
      <li year="1994"> The company released its first game, King's Field, for the PlayStation in 1994. (Japan only)
      </li>
      <li year="1995"> It went on to release King's Field II and III internationally in 1995 and 1996. </li>
      <li year="1997"> In 1997, FromSoftware released the first Armored Core series game. </li>
      <li year="2009"> The company started a new gaming genre called "Soulslike" with the release of
        Demon's Souls in 2009. </li>
      <li year="2009"> In 2011, they released Dark Souls I which found huge commercial success and had 2 sequels </li>
      <li year="2015"> They released Bloodborne in 2015 exclusively on the PlayStation 4. </li>
      <li year="2022"> In 2022, FromSoftware released Elden Ring their most successful game ever and sold over 28.6
        million copies worldwide. </li>
    </ul>
  </milestones>
  <current_projects>
    <p>
      This is purely speculation but a Bloodborne Remaster or sequel could be worked on to coincide with the launch of
      Playstation 6, which would be around 2028.
    </p>
  </current_projects>
</overview>  
<notable_games>
  <game>
    <gamedata>
      <game_name> Demon's Souls </game_name>
      <released year="2009"/>
      <publisher> Sony (JP) - Atlus (NA) - Bandai Namco (PAL) </publisher>
      <platforms> PlayStation 3 </platforms>
      <genre> Action role-playing </genre>
    </gamedata>
    <description>
      <p>
      Demon's Souls is set in Boletaria, a kingdom consumed by a dark being called the Old One, following its release
      through the use of forbidden Soul Arts. Players take on the role of a hero brought to Boletaria to kill its fallen
      king Allant and pacify the Old One. Gameplay has players navigating five different worlds from a hub called the
      Nexus, with a heavy emphasis on challenging combat and mechanics surrounding player death and respawning. Online
      multiplayer allows both player cooperation and world invasions featuring player versus player combat.
      </p>
    </description>
    <awards>
      <ul>
        <li year="2009"> Game of the Year, Best PS3 game, Best Role-Playing game and Best Original Game Mechanic
          for the online integration awards by GameSpot in 2009. </li>
        <li year="2010"> Best RPG and Best New intellectual property by GameTrailers. </li>
        <li year="2009"> Best RPG for the PS3 by IGN. </li>
      </ul>
    </awards>
  </game>
  <game>
    <gamedata>
      <game_name> Bloodborne</game_name>
      <released year="2015"/>
      <publisher> Sony </publisher>
      <platforms> PlayStation 4 </platforms>
      <genre> Action role-playing </genre>
    </gamedata>
    <description>
      <p>
      Bloodborne is an action role-playing game played from a third-person perspective and features elements similar
      to those found in the Dark Souls series, also made by FromSoftware. The player makes their way through different
      locations within the decrepit Gothic world of Yharnam while battling varied enemies, including bosses,collecting
      different types of items that have many uses, interacting with non-player characters, opening up shortcuts,
      and continuing through the main story.
      </p>
    </description>
    <awards>
      <p>
        Bloodborne was awarded the 2015 Game of the Year by several video game review sites, including GameTrailers,
        Eurogamer, Destructoid, and Edge, along with being awarded the "2015 PlayStation 4 Game of the Year" by IGN. 
        In 2015, Edge rated it the fourth greatest video game of all time. A 2023 poll conducted by GQ which surveyed a 
        team of video game journalists across the industry ranked Bloodborne as the fourth best video game of all time.
      </p>
    </awards>
  </game>
  <game>
    <gamedata>
      <game_name> Elden Ring </game_name>
      <released year="2022"/>
      <publisher> Bandai Namco </publisher>
      <platforms>PC - PlayStation 4/5 - Xbox One/Series SX </platforms>
      <genre> Action role-playing </genre>
    </gamedata>
    <description>
      <p>
        Elden Ring is a 2022 action role-playing game developed by FromSoftware. It was directed by Hidetaka Miyazaki
        with worldbuilding provided by American fantasy writer George R. R. Martin. It was published for PlayStation 4,
        PlayStation 5, Windows, Xbox One, and Xbox Series X/S on February 25 in Japan by FromSoftware and
        internationally by Bandai Namco Entertainment. Set in the Lands Between, players control a customizable player
        character on a quest to repair the Elden Ring and become the new Elden Lord.
      </p>
    </description>
    <awards>
      <p>
        Elden Ring received over 300 Game of the Year awards, including by the publications Ars Technica, Destructoid,
        EGM, Eurogamer, Game Informer, GamesRadar+, GameSpot, IGN, PC Gamer, and Polygon.
      </p>
    </awards>
  </game>
</notable_games>
<illustrations>
  <img src="../Images/FromSoftware/Bloodborne.jpg" alt="Bloodborne"/>
  <img src="../Images/FromSoftware/Demon's_souls.jpg" alt="Demon's Souls"/>
  <img src="../Images/FromSoftware/Elden_ring.jpg" alt="Elden Ring"/>
  <img src="../Images/FromSoftware/FromSoftware.png" alt="FromSoftware"/>
  <img src="../Images/FromSoftware/Hidetaka_Miyazaki.png" alt="Hidetaka Miyazaki"/>
</illustrations>
</game_studios>

=== bahaeddine73/Site-Web/XML/NaughtyDog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game_studios SYSTEM "game_studios.dtd">
<game_studios status="active" main_genre="Action-adventure" year_of_first_game_published="1986" id="1">
    <studiodata>
        <name> Naughty Dog </name>
        <headquarters> 	Santa Monica, California, US </headquarters>
        <founded year="1984"/>
        <key_people title="head of creative/president"> Neil Druckmann </key_people>
        <key_people title="studio manager">Alison Mori </key_people>
        <key_people title="co-founder"> Andy Gavin </key_people>
        <key_people title="co-founder"> Jason Rubin </key_people>
        <number_of_employees month="7" year="2023"> 400+ </number_of_employees>
    </studiodata>
    <overview>
        <history>
            <p>
                Naughty Dog is an American first-party video game developer based in Santa Monica, California. Founded
                by Andy Gavin and Jason Rubin in 1984, the studio was acquired by Sony Computer Entertainment in 2001.
                Gavin and Rubin produced a sequence of progressively more successful games, including Rings of Power and
                Way of the Warrior in the early 1990s. The latter game prompted Universal Interactive Studios to sign
                the duo to a three-title contract and fund the expansion of the company.
            </p>
            <p>
                After designer and producer Mark Cerny convinced Naughty Dog to create a character-based platform game
                that would use the 3D capabilities of the new systems, Naughty Dog created Crash Bandicoot for the
                PlayStation in 1996. Naughty Dog developed three Crash Bandicoot games over the next several years.
                After developing Crash Team Racing, the company began working on Jak and Daxter: The Precursor Legacy
                for the PlayStation 2.
            </p>
            <p>
                In 2004, Rubin, who had become the company's president, left the company to work on a new project,
                Iron and the Maiden. In addition to their inhouse game team, Naughty Dog is also home to the ICE Team,
                one of PlayStation Studios's central technology groups. The company's first PlayStation 3 game,
                Uncharted: Drake's Fortune, was released in 2007, followed by several sequels and spin-off titles. This
                lasted until Naughty Dog announced a new intellectual property for the PlayStation 3, The Last of Us,
                which was in development by a secondary team at the studio and released to critical acclaim in 2013
                which spawned a franchise. The Last of Us Part II was released for the PlayStation 4 in 2020 to similar
                acclaim. The studio is developing Intergalactic: The Heretic Prophet for the PlayStation 5.
            </p>
        </history>
        <milestones>
            <ul>
                <li year="1989">In 1989, the studio was renamed from JAM Software to Naughty Dog.</li>
                <li year="1996">The Crash Bandicoot series was started in 1996 with a release exclusive for the PS.</li>
                <li year="2001">In 2001, Sony bought Naughty Dog and made them a first-party studio.</li>
                <li year="2007">Uncharted was released in 2007, starting a franchise that would sell over 40 million
                    copies.</li>
                <li year="2013">The Last of Us was released in 2013 for the PS3, and it won game of the year.</li>
                <li year="2017">In 2017, Uncharted: The Lost Legacy was the final installment in the series.</li>
                <li year="2020">The Last of Us Part II was released in summer 2020 for the PS4.</li>
            </ul>
        </milestones>
        <current_projects>
            <p>
                Naughty Dog’s next game is Intergalactic: The Heretic Prophet, currently in development for the
                PlayStation 5 console. They’ve been working on this since 2020.
            </p>
        </current_projects>
    </overview>
    <notable_games>
        <game>
            <gamedata>
                <game_name> The Last of Us</game_name>
                <released year="2013"/>
                <publisher> Sony Computer Entertainment</publisher>
                <platforms> PlayStation 3</platforms>
                <genre> Action-adventure</genre>
            </gamedata>
            <description>
                <p>
                    The Last of Us is an action-adventure game played from a third-person perspective. The player
                    traverses post-apocalyptic environments such as towns, buildings, forests, and sewers to advance the
                    story. The player can use firearms, improvised weapons, hand-to-hand combat, and stealth to defend
                    against hostile humans and cannibalistic creatures infected by a mutated strain of the Cordyceps
                    fungus. For most of the game, the player takes control of Joel, a man tasked with escorting a young
                    girl, Ellie, across the United States. The player also controls Ellie throughout the game's winter
                    segment and briefly controls Joel's daughter, Sarah, in the opening sequence.
                </p>
            </description>
            <awards>
                <ul>
                    <li year="2013">Best Overall Sound, Best PlayStation 3 Multiplayer, and Best Action-Adventure Game
                        on PlayStation 3 and overall at IGN's Best of 2013 Awards.</li>
                    <li year="2014">Best Third Person Shooter from GameTrailers.</li>
                    <li year="2014">Adventure Game of the Year at the D.I.C.E. Awards.</li>
                </ul>
            </awards>
        </game>
        <game>
            <gamedata>
                <game_name>Uncharted 4: A Thief's End</game_name>
                <released year="2016"/>
                <publisher>	Sony Computer Entertainment</publisher>
                <platforms>PlayStation 4</platforms>
                <genre>Action-adventure, third-person shooter</genre>
            </gamedata>
            <description>
                <p>
                    Uncharted 4: A Thief's End is the fourth main entry in the Uncharted series. Set several years after
                    the events of Uncharted 3: Drake's Deception, players control Nathan Drake, a former treasure hunter
                    coaxed out of retirement by his presumed-dead brother Samuel. With Nathan's longtime partner, Victor
                    Sullivan, they search for clues to the location of Henry Avery's long-lost treasure. A Thief's End
                    is played from a third-person perspective, and incorporates platformer elements. Players solve
                    puzzles and use firearms, melee combat, and stealth to combat enemies. In the online multiplayer
                    mode, up to ten players engage in co-operative and competitive modes.
                </p>
            </description>
            <awards>
                <p>
                    Uncharted 4: A Thief's End received "universal acclaim" according to review aggregator Metacritic.
                    It is the joint sixth-highest rated PlayStation 4 game on Metacritic. Reviewers praised the gameplay
                    mechanics, narrative, emotional depth, visual design, and the multiplayer mode. IGN's Lucy O'Brien
                    wrote that the game is "a remarkable achievement in blockbuster storytelling and graphical beauty";
                    GameSpot's Mike Mahardy similarly named it a "breathtaking marvel of a game". GamesTM considered it
                    "a masterful piece of storytelling", and Electronic Gaming Monthly's Nick Plessas declared it
                    "a true work of art".
                </p>
            </awards>
        </game>
        <game>
            <gamedata>
                <game_name>The Last of Us Part II</game_name>
                <released year="2020"/>
                <publisher>	Sony Interactive Entertainment</publisher>
                <platforms>PlayStation 4</platforms>
                <genre>	Action-adventure</genre>
            </gamedata>
            <description>
                <p>
                    Set four years after The Last of Us (2013), the game focuses on two playable characters in a
                    post-apocalyptic United States whose lives intertwine: Ellie, who sets out in revenge for a murder,
                    and Abby, a soldier who becomes involved in a conflict between her militia and a religious cult.
                    The game uses a third-person perspective; the player must fight human enemies and zombie-like
                    creatures with firearms, improvised weapons, and stealth.
                </p>
            </description>
            <awards>
                <p>
                    The Last of Us Part II won more than 320 Game of the Year awards, which several outlets claimed
                    broke the record set by The Witcher 3: Wild Hunt (2015). The game was awarded from outlets and shows
                    such as Den of Geek, Digital Trends, Electronic Gaming Monthly, Empire, Entertainment Weekly,
                    Game Informer, PlayStation Blog, Push Square, and the Titanium Awards. It was named runner-up by
                    several other publications. 
                </p>
            </awards>
        </game>
    </notable_games>
    <illustrations>
        <img src="../Images/NaughtyDog/NaughtyDog.png" alt="Naughty Dog logo"/>
        <img src="../Images/NaughtyDog/Neil_Druckmann.jpg" alt="Neil Druckmann"/>
        <img src="../Images/NaughtyDog/The_Last_of_Us.jpg" alt="The Last of Us"/>
        <img src="../Images/NaughtyDog/Uncharted_4.jpg" alt="Uncharted 4"/>
        <img src="../Images/NaughtyDog/TLOU2.png" alt="The Last of Us Part II"/>
    </illustrations>
</game_studios>
