=== bahaeddine73/Site-Web/XML/game_studios.dtd
<!ENTITY % monthval "(1|2|3|4|5|6|7|8|9|10|11|12)">
<!ENTITY % dayval
	 "(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)">  
<!ENTITY % year "CDATA"> 
<!ENTITY % amp  "&#38;">


<!ENTITY % inline "img | keyword | a | highlight">
<!ENTITY % datainline "(#PCDATA | %inline; )*">
<!ENTITY % datainlineul "(#PCDATA | p | %inline; | ul)*">

<!ENTITY % coreattrs
	 "id       ID      #IMPLIED
	  class    CDATA   #IMPLIED
	  title    CDATA   #IMPLIED"
>

<!ENTITY % URI "CDATA">
 <!-- a Uniform Resource Identifier, see [RFC2396] -->

<!ENTITY % Length "CDATA">
<!-- nn for pixels or nn% for percentage length -->


<!ENTITY % Text "CDATA">
    <!-- used for titles etc. -->

    
<!ELEMENT game_studios
	  (studiodata,citation?,overview,notable_games,illustrations?)>

<!ATTLIST game_studios
	  %coreattrs;
	  id  ID #REQUIRED
	  main_genre    %Text;   #IMPLIED
	  status    (active|defunct)  #IMPLIED
	  year_of_first_game_published      %year;   #REQUIRED>

<!ELEMENT studiodata (name,headquarters+,founded,key_people+,number_of_employees)>
<!ATTLIST studiodata
	  %coreattrs;>

<!ELEMENT name %datainline;>
<!ATTLIST name
	  %coreattrs;>

<!ELEMENT headquarters %datainline;>
<!ATTLIST headquarters
	  %coreattrs;>

<!ELEMENT founded EMPTY>
<!ATTLIST founded
	  %coreattrs;
	  year     %year;       #REQUIRED
	  month    %monthval;   #IMPLIED
	  day      %dayval;     #IMPLIED
	  >

<!ELEMENT key_people %datainline;>
<!ATTLIST key_people
	  %coreattrs;
	  title  %Text;   #IMPLIED>

<!ELEMENT number_of_employees %datainline;>
<!ATTLIST number_of_employees
	%coreattrs;
	year     %year;       #IMPLIED
	month    %monthval;   #IMPLIED
	>

<!ELEMENT citation %datainline;>
<!ATTLIST citation
	  %coreattrs;
	  author %Text; #REQUIRED>



<!ELEMENT overview (history,milestones,current_projects*)>
<!ATTLIST overview
	  %coreattrs;
	  >


<!ELEMENT history %datainlineul;>
<!ATTLIST history
	  %coreattrs;
	  >

<!ELEMENT milestones %datainlineul;>
<!ATTLIST milestones
	  %coreattrs;
	  >


<!ELEMENT current_projects %datainlineul;>
<!ATTLIST current_projects
	  %coreattrs;
	  >



<!ELEMENT notable_games (game+)+>

<!ELEMENT game (gamedata,description,awards*)>
<!ATTLIST game
      %coreattrs;
      >

<!ELEMENT gamedata (game_name,released,publisher,platforms,genre)>
<!ATTLIST gamedata
				%coreattrs;>


<!ELEMENT game_name %datainline;>
<!ATTLIST game_name
		%coreattrs;>


<!ELEMENT released EMPTY>
<!ATTLIST released
		%coreattrs;
		year     %year;       #REQUIRED
		month    %monthval;   #IMPLIED?
		day      %dayval;     #IMPLIED
		>


<!ELEMENT publisher %datainline;>
<!ATTLIST publisher
		%coreattrs;>


<!ELEMENT platforms %datainline;>
<!ATTLIST platforms
		%coreattrs;>


<!ELEMENT genre %datainline;>
<!ATTLIST genre
		%coreattrs;>


<!ELEMENT description %datainlineul;>
<!ATTLIST description
    	%coreattrs;>


<!ELEMENT awards %datainlineul;>
<!ATTLIST awards
		%coreattrs;>



<!ELEMENT ul (li+)>

<!ELEMENT li %datainlineul;>
<!ATTLIST li
	  %coreattrs;
	  year     %year;       #REQUIRED
      month    %monthval;   #IMPLIED
      day      %dayval;     #IMPLIED
	  >


<!ELEMENT illustrations (img+)>
<!ATTLIST illustrations
	  %coreattrs;
	  >


<!ELEMENT img EMPTY>
<!ATTLIST img
	  %coreattrs;
	  src         %URI; #REQUIRED
	  alt         %Text; #REQUIRED
	  longdesc    %URI;          #IMPLIED
	  height      %Length;       #IMPLIED
	  width       %Length;       #IMPLIED
	  >



<!ELEMENT a (#PCDATA)*>
<!ATTLIST a
  %coreattrs;
  href        %URI;          #IMPLIED
>


<!ELEMENT highlight %datainline;>
<!ATTLIST highlight
	  %coreattrs;
	  >

<!ELEMENT p %datainline;>
<!ATTLIST p 
	  %coreattrs;
	  >

=== bahaeddine73/Site-Web/XML/rockstar-studio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game_studios SYSTEM "game_studios.dtd">
<game_studios status="active" main_genre="Action-adventure" year_of_first_game_published="1997" id="3">
    <studiodata>
        <name>Rockstar Games</name>
        <headquarters>New York, United States</headquarters>
        <founded day="12" month="3" year="1998"/>
        <key_people title="founder">Sam Houser</key_people>
        <key_people title="president">Sam Houser</key_people>
        <number_of_employees month="2" year="2025">Around 2,000</number_of_employees>
    </studiodata>
    <citation author="Sam Houser">We’ve always wanted to create games that push the boundaries and offer immersive experiences.</citation>
    <overview>
        <history>
            <p>Rockstar Games is an American video game publisher founded in 1998 by Sam Houser, Dan Houser, Terry Donovan, Jamie King, and Gary Foreman. The company is best known for its successful "Grand Theft Auto" series, which began in 1997 under the development of DMA Design, later renamed Rockstar North. Over the years, Rockstar Games has expanded its portfolio with franchises such as "Red Dead", "Max Payne", and "Midnight Club".</p>
            <p>In 2014, Rockstar Games was honored with a BAFTA Academy Fellowship Award for its outstanding contribution to the video game industry. That same year, founders Sam and Dan Houser were inducted into the Hall of Fame of the Academy of Interactive Arts and Sciences. In 2020, Dan Houser left the company to pursue other projects, leaving Sam Houser in charge of the company.</p>
        </history>
        <milestones>
            <ul>
                <li year="1997">Release of the first "Grand Theft Auto", marking the beginning of an iconic franchise.</li>
                <li year="2001">Launch of "Grand Theft Auto III", introducing a 3D perspective and open-world, revolutionizing the genre.</li>
                <li year="2010">Release of "Red Dead Redemption", a critically acclaimed game set in the American West.</li>
                <li year="2013">Launch of "Grand Theft Auto V", becoming the second best-selling game of all time with over 200 million copies sold.</li>
                <li year="2018">Release of "Red Dead Redemption 2", praised for its narrative depth and detailed world.</li>
            </ul>
        </milestones>
        <current_projects>
            <p>Although Rockstar Games has not officially announced new projects, persistent rumors suggest the development of "Grand Theft Auto VI". Fans also speculate about potential remasters of classic titles for next-gen consoles.</p>
        </current_projects>
    </overview>
    <notable_games>
        <game>
            <gamedata>
                <game_name>Grand Theft Auto V</game_name>
                <released year="2013"/>
                <publisher>Rockstar Games</publisher>
                <platforms>PlayStation 3, PlayStation 4, PlayStation 5, Xbox 360, Xbox One, Xbox Series X/S, PC</platforms>
                <genre>Action-adventure</genre>
            </gamedata>
            <description>
                <p>"Grand Theft Auto V" follows the story of three criminals in the fictional city of Los Santos, allowing players to switch between protagonists. The game is known for its expansive and detailed open world, as well as its multiplayer mode, "GTA Online".</p>
            </description>
            <awards>
                <ul>
                    <li year="2013">Game of the Year by multiple publications, including GameSpot and IGN.</li>
                    <li year="2014">BAFTA Games Award for Best British Game.</li>
                </ul>
            </awards>
        </game>
        <game>
            <gamedata>
                <game_name>Red Dead Redemption 2</game_name>
                <released year="2018"/>
                <publisher>Rockstar Games</publisher>
                <platforms>PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC</platforms>
                <genre>Action-adventure</genre>
            </gamedata>
            <description>
                <p>"Red Dead Redemption 2" is a prequel to the original game, set in 1899 and following the outlaw Arthur Morgan. The game is praised for its immersive storytelling, rich open world, and realistic details.</p>
            </description>
            <awards>
                <ul>
                    <li year="2018">Game Awards: Best Narrative.</li>
                    <li year="2019">BAFTA Games Award for Best Game.</li>
                </ul>
            </awards>
        </game>
    </notable_games>
    <illustrations>
        <img src="../Images/Rockstarstudio/rockstarphoto" alt="Rockstar Games logo"/>
        <img src="../Images/Rockstarstudio/photo of the game_1.png" alt="Rockstar Games logo"/>
        <img src="../Images/Rockstarstudio/photo of the game_1.1.png" alt="Rockstar Games logo"/>
        <img src="../Images/Rockstarstudio/photo of the game_2.png" alt="Rockstar Games logo"/>
        <img src="../Images/Rockstarstudio/photo of the game_2.2.png" alt="Rockstar Games logo"/>
    </illustrations>
</game_studios>
